Repository DiscordValley/TheValley, pull requests merged in 2020-10, with the labels that each got.

#54 WIP: Algorithms
  bot/game/player.py
  bot/utils/formulas.py
Labels: base

#59 Format Responses / Profile Command
  bot/__init__.py
  bot/cogs/profile.py
  bot/cogs/store.py
Labels: hacktoberfest-accepted

#60 Update ;info title and properly fetch prefix
  bot/cogs/utility.py
Labels: bug, hacktoberfest-accepted
